#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
# setxkbmap -layout latam

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
pulseaudio &
nm-applet &
pidgin & 
slack & 
wmname LG3D && PYCHARM_JDK=/usr/lib/jvm/java-6-openjdk-amd64 /home/nigel/Downloads/pycharm-2016.2.3/bin/pycharm.sh &
exec fluxbox
# or if you want to keep a log:

# exec fluxbox -log "/home/enrique/.fluxbox/log"
